name: yonaki
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_unity_widget: ^0.1.6+5
  location: ^3.0.2
  latlong: ^0.6.1
  animated_text_kit: ^2.2.0
  provider: ^4.2.0
  reorderables: ^0.3.2
  quiver: ^2.1.3
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  google_maps_flutter: ^0.5.28+1
  http: ^0.12.2
  percent_indicator: ^2.1.5
  audioplayers: ^0.15.1
  modal_progress_hud: ^0.1.3
  firebase_storage: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Horror
      fonts:
        - asset: fonts/horror.otf
